#!/usr/bin/env python
import sys
import xapi.storage.libs.xcpng.cluster_stack.consul.ha as ha
from xapi.storage import log
from xapi.storage.libs.xcpng.utils import call

log.debug('HA ha_query_liveset')

try:
    liveness = {}
    ismaster = {}
    uuid = {}
    liveset = ""

    sf = ha.Statefile()

    master = sf.get_master()
    master_uuid = master.uuid

    pool_state_invalid = sf.get_invalid()
    if pool_state_invalid:
        call("HA", ["/usr/libexec/xapi/cluster-stack/consul/ha_stop_daemon"])
        sys.exit(14)

    hosts = sf.read_all_hosts()
    nodeids = []

    for hostid in hosts.keys():
        host_uuid = hosts[hostid].uuid
        if host_uuid:
            nodeids.append(hostid)
            uuid[hostid] = host_uuid
            liveness[hostid] = "FALSE"
            if master_uuid == host_uuid:
                ismaster[hostid] = "TRUE"
            else:
                ismaster[hostid] = "FALSE"

    hosts_with_running_xapi = ha.get_xapi_ha_lockspace_members()

    for hostid in hosts.keys():
        if hosts[hostid].online:
            if hostid in hosts_with_running_xapi:
                    liveness[hostid] = "TRUE"
                    liveset += (" " + uuid[hostid])
            else:
                liveness[hostid] = "FALSE"

except Exception:
    log.error("HA ha_query_liveset error", exc_info=True)
    print "HA pool state invalid"
    sys.exit(0)

out = """<?xml version="1.0" encoding="UTF-8"?>
<ha_liveset_info version="1.0">
  <status>Online</status>
  <localhost>
    <HostID>%s</HostID>
  </localhost>""" % ha.xapi_host_uuid

for hostid in nodeids:
    out += """
  <host>
    <HostID>%s</HostID>
    <liveness>%s</liveness>
    <master>%s</master>
    <statefile_access>%s</statefile_access>
    <statefile_corrupted>FALSE</statefile_corrupted>
    <excluded>FALSE</excluded>
  </host>""" % (uuid[hostid], liveness[hostid],
                ismaster[hostid], liveness[hostid])

out += """
  <raw_status_on_local_host>
    <statefile_latency>1</statefile_latency>
    <statefile_latency_max>1</statefile_latency_max>
    <statefile_latency_min>0</statefile_latency_min>
    <heartbeat_latency>7006</heartbeat_latency>
    <heartbeat_latency_max>7006</heartbeat_latency_max>
    <heartbeat_latency_min>7006</heartbeat_latency_min>
    <Xapi_healthcheck_latency>27</Xapi_healthcheck_latency>
    <Xapi_healthcheck_latency_max>-1</Xapi_healthcheck_latency_max>
    <Xapi_healthcheck_latency_min>-1</Xapi_healthcheck_latency_min>"""

for hostid in nodeids:
    if liveness[hostid] == "TRUE":
        out += """
    <host_raw_data>
      <HostID>%s</HostID>
      <time_since_last_update_on_statefile>7304</time_since_last_update_on_statefile>
      <time_since_last_heartbeat>3839</time_since_last_heartbeat>
      <time_since_xapi_restart_first_attempted>-1</time_since_xapi_restart_first_attempted>
      <xapi_error_string></xapi_error_string>
      <heartbeat_active_list_on_heartbeat>
          %s
      </heartbeat_active_list_on_heartbeat>
      <heartbeat_active_list_on_statefile>
          %s
      </heartbeat_active_list_on_statefile>
      <statefile_active_list_on_heartbeat>
          %s
      </statefile_active_list_on_heartbeat>
      <statefile_active_list_on_statefile>
          %s
      </statefile_active_list_on_statefile>
    </host_raw_data>""" % (uuid[hostid], liveset, liveset, liveset, liveset)
    else:
        out += """
    <host_raw_data>
      <HostID>%s</HostID>
      <time_since_last_update_on_statefile>7304</time_since_last_update_on_statefile>
      <time_since_last_heartbeat>3839</time_since_last_heartbeat>
      <time_since_xapi_restart_first_attempted>-1</time_since_xapi_restart_first_attempted>
      <xapi_error_string></xapi_error_string>
      <heartbeat_active_list_on_heartbeat>
      </heartbeat_active_list_on_heartbeat>
      <heartbeat_active_list_on_statefile>
      </heartbeat_active_list_on_statefile>
      <statefile_active_list_on_heartbeat>
      </statefile_active_list_on_heartbeat>
      <statefile_active_list_on_statefile>
      </statefile_active_list_on_statefile>
    </host_raw_data>""" % (uuid[hostid])

out += """
  </raw_status_on_local_host>
  <timeout>
    <T1>60000</T1>
    <T2>60000</T2>
    <T3>120000</T3>
    <Wh>60000</Wh>
    <Ws>75000</Ws>
  </timeout>
  <warning_on_local_host>
    <statefile_lost>FALSE</statefile_lost>
    <heartbeat_approaching_timeout>FALSE</heartbeat_approaching_timeout>
    <statefile_approaching_timeout>FALSE</statefile_approaching_timeout>
    <Xapi_healthcheck_approaching_timeout>FALSE</Xapi_healthcheck_approaching_timeout>
    <network_bonding_error>FALSE</network_bonding_error>
  </warning_on_local_host>
</ha_liveset_info>"""

print out
