#!/usr/bin/env python
import sys
import xapi.storage.libs.xcpng.cluster_stack.consul.ha as ha
import time
import subprocess
from xapi.storage import log

log.debug('HA ha_propose_master')

timeout = 30

arg = ["/usr/libexec/xapi/cluster-stack/consul/ha_master_lock"]
ha_master_lock_process = subprocess.Popen(arg)

sf = ha.Statefile()

for i in range(timeout):
    master = sf.get_master()
    if master.uuid == ha.xapi_host_uuid:
        print "TRUE"
        sys.exit(0)
    else:
        time.sleep(1)

print "FALSE"
